add mha-service script

diff --git a/samples/scripts/mha-service b/samples/scripts/mha-service
--- a/samples/scripts/mha-service
+++ b/samples/scripts/mha-service
@@ -1,4 +1,17 @@
 #! /bin/sh
+#
+# $Id:$
+#
+# mha:       Starts the masterha_manager as Daemon
+#
+# Version:     1.0 
+#
+# chkconfig: 2345 90 10
+# description: Start & Ends masterha_manager as a Daemon \
+#
+# processname: masterha_manager
+# config: /etc/mha/
+
 . /lib/lsb/init-functions
 
 CLUSTER='group';
@@ -6,16 +19,21 @@ CONF=/etc/mha/${CLUSTER}.cnf
 LOGFILE=/var/log/masterha/${CLUSTER}/${CLUSTER}.log  
 
 start () {
+    echo "Starting $CLUSTER..."
     command_ls=`nohup masterha_manager --conf=$CONF --manager_log=${LOGFILE} < /dev/null >> $LOGFILE 2>&1 &`
-
-    log_daemon_msg "Starting $CLUSTER"
+    if [[ $? eq 0 ]]
+    then 
+        echo 'Success';
+    else
+        echo 'Failed';
+    fi
 }
 stop () {
-    log_daemon_msg "Stopping $CLUSTER"
+    echo "Stopping $CLUSTER"
     start-stop-daemon --stop --quiet --oknodo --pidfile "$pid_file"
 }
 status () {
-    log_daemon_msg "Status of $CLUSTER"
+    echo "Status of $CLUSTER"
     masterha_check_status --conf=${CONF}
 
 }
